spring.application.name=fudbalski_klub

### POSTGRES DATABASE ###
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

### JPA HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

### JWT ###
jwt.secret=${JWT_SECRET}

### RABBITMQ ###
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

### LOGGING ###
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG

### LLM SERVICE ###
football.ai-service.base-url=${FOOTBALL_AI_SERVICE_BASE_URL}

### API FOOTBALL ###
api.football.base-url=${API_FOOTBALL_BASE_URL}
api.football.key=${API_FOOTBALL_KEY}
scouting.simulation.current-date=2024-09-06

server.forward-headers-strategy=framework

