spring.application.name=fudbalski_klub

### POSTGRES DATABASE ###
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

### JPA HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

### JWT ###
jwt.secret=${JWT_SECRET}

### INFLUXDB ###
influxdb.url=${INFLUXDB_URL}
influxdb.token=${INFLUXDB_TOKEN}
influxdb.org=${INFLUXDB_ORG}
influxdb.bucket=${INFLUXDB_BUCKET}

### NEO4J ###
spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

### LOGGING ###
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG

### LLM SERVICE ###
football.ai-service.base-url=${FOOTBALL_AI_SERVICE_BASE_URL}

### API FOOTBALL ###
api.football.base-url=${API_FOOTBALL_BASE_URL}
api.football.key=${API_FOOTBALL_KEY}
scouting.simulation.current-date=2024-04-12

server.forward-headers-strategy=framework

